<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Order;
use App\Models\OrderItem;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        $orders = [
            [
                'code' => 'ASC-1051',
                'user_id' => null,
                'customer' => 'Bayu Pratama',
                'phone' => null,
                'email' => null,
                'total' => 425000,
                'shipping_cost' => 0,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '18 Jun',
                'type' => 'ready',
                'status' => 'Paid',
                'order_items' => [
                    // No order_items in DB for this order
                ],
            ],
            [
                'code' => 'PO-MSZIG6Y278',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 670000,
                'shipping_cost' => 10000,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '19 Agu 2026',
                'type' => 'preorder',
                'status' => 'Paid',
                'order_items' => [
                    ['product_id' => 7, 'size' => 'M', 'color' => 'Off-White', 'qty' => 1, 'type' => 'preorder', 'price' => 220000],
                    ['product_id' => 7, 'size' => 'S', 'color' => 'Sand', 'qty' => 2, 'type' => 'preorder', 'price' => 220000],
                ],
            ],
            [
                'code' => 'PO-MSZJMGRR22',
                'user_id' => null,
                'customer' => 'Dika Maulana',
                'phone' => '0812431231',
                'email' => 'mdika8140@gmail.com',
                'total' => 670000,
                'shipping_cost' => 10000,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '19 Agu 2026',
                'type' => 'preorder',
                'status' => 'Paid',
                'order_items' => [
                    ['product_id' => 7, 'size' => 'XL', 'color' => 'Off-White', 'qty' => 2, 'type' => 'preorder', 'price' => 220000],
                    ['product_id' => 7, 'size' => 'XL', 'color' => 'Sand', 'qty' => 1, 'type' => 'preorder', 'price' => 220000],
                ],
            ],
            [
                'code' => 'TEST-API-001',
                'user_id' => null,
                'customer' => 'API Test',
                'phone' => null,
                'email' => null,
                'total' => 100000,
                'shipping_cost' => 0,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '20 Aug',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [],
            ],
            [
                'code' => 'ASC-MT1BULV239',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 83000,
                'shipping_cost' => 25000,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '20 Agu 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 19, 'size' => '3L', 'color' => 'Navy', 'qty' => 2, 'type' => 'ready', 'price' => 16000],
                    ['product_id' => 19, 'size' => 'S', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 16000],
                ],
            ],
            [
                'code' => 'ASC-MT2F05SC79',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 83000,
                'shipping_cost' => 25000,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '21 Agu 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 19, 'size' => '3L', 'color' => 'Navy', 'qty' => 2, 'type' => 'ready', 'price' => 16000],
                    ['product_id' => 19, 'size' => 'S', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 16000],
                ],
            ],
            [
                'code' => 'ASC-MT2MHUT751',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 56000,
                'shipping_cost' => 44000,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '21 Agu 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 23, 'size' => 'XS', 'color' => 'Charcoal', 'qty' => 1, 'type' => 'ready', 'price' => 12000],
                ],
            ],
            [
                'code' => 'ASC-MT2MHWI460',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 56000,
                'shipping_cost' => 44000,
                'shipping_service' => null,
                'payment_method' => 'transfer_bca',
                'date' => '21 Agu 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 23, 'size' => 'XS', 'color' => 'Charcoal', 'qty' => 1, 'type' => 'ready', 'price' => 12000],
                ],
            ],
            [
                'code' => 'ASC-MT2PRY334',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 141000,
                'shipping_cost' => 125000,
                'shipping_service' => null,
                'payment_method' => 'va',
                'date' => '21 Agu 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 19, 'size' => 'S', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 16000],
                ],
            ],
            [
                'code' => 'ASC-MT2PTMCV73',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 191000,
                'shipping_cost' => 175000,
                'shipping_service' => null,
                'payment_method' => 'qris',
                'date' => '21 Agu 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 19, 'size' => 'M', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 16000],
                ],
            ],
            [
                'code' => 'ASC-MT6L7OEE67',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 57000,
                'shipping_cost' => 41000,
                'shipping_service' => null,
                'payment_method' => 'qris',
                'date' => '24 Agu 2026',
                'type' => 'ready',
                'status' => 'Paid',
                'order_items' => [
                    ['product_id' => 19, 'size' => 'XL', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 16000],
                ],
            ],
            [
                'code' => 'ASC-MT6OXU1V78',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 178000,
                'shipping_cost' => 132000,
                'shipping_service' => null,
                'payment_method' => 'qris',
                'date' => '24 Agu 2026',
                'type' => 'ready',
                'status' => 'Paid',
                'order_items' => [
                    ['product_id' => 27, 'size' => '3L', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 12000],
                    ['product_id' => 27, 'size' => 'S', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 12000],
                    ['product_id' => 27, 'size' => 'XL', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 12000],
                ],
            ],
            [
                'code' => 'ASC-MT6PXF2Y20',
                'user_id' => 2,
                'customer' => 'User Demo',
                'phone' => '08123123123',
                'email' => 'user@aircooled.com',
                'total' => 66000,
                'shipping_cost' => 44000,
                'shipping_service' => null,
                'payment_method' => 'qris',
                'date' => '24 Agu 2026',
                'type' => 'ready',
                'status' => 'Paid',
                'order_items' => [
                    ['product_id' => 27, 'size' => 'XXL', 'color' => 'Black', 'qty' => 1, 'type' => 'ready', 'price' => 12000],
                ],
            ],
            [
                'code' => 'PO-MT6WLZ5C41',
                'user_id' => null,
                'customer' => 'Dimas',
                'phone' => '081231231',
                'email' => 'dimas@gmail.com',
                'total' => 44000,
                'shipping_cost' => 44000,
                'shipping_service' => null,
                'payment_method' => null,
                'date' => '24 Agu 2026',
                'type' => 'preorder',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 28, 'size' => 'S', 'color' => 'Navy', 'qty' => 1, 'type' => 'preorder', 'price' => 0],
                ],
            ],
            [
                'code' => 'ASC-MTMED69J85',
                'user_id' => null,
                'customer' => 'Dimas',
                'phone' => '08134324242',
                'email' => 'dimas@gmail.com',
                'total' => 56000,
                'shipping_cost' => 44000,
                'shipping_service' => 'REG - Layanan Reguler',
                'payment_method' => 'qris',
                'date' => '04 Sep 2026',
                'type' => 'ready',
                'status' => 'Paid',
                'order_items' => [
                    ['product_id' => 24, 'size' => 'XL', 'color' => 'Off-White', 'qty' => 1, 'type' => 'ready', 'price' => 12000],
                ],
            ],
            [
                'code' => 'PO-MTMEVQ0730',
                'user_id' => null,
                'customer' => 'Dani',
                'phone' => '08123213',
                'email' => 'mdika@gmail.com',
                'total' => 66000,
                'shipping_cost' => 44000,
                'shipping_service' => null,
                'payment_method' => null,
                'date' => '04 Sep 2026',
                'type' => 'preorder',
                'status' => 'Awaiting',
                'order_items' => [
                    ['product_id' => 33, 'size' => 'S', 'color' => 'Sand', 'qty' => 1, 'type' => 'preorder', 'price' => 22000],
                ],
            ],
            [
                'code' => 'ASC-MTMK1I1R15',
                'user_id' => 3,
                'customer' => 'Dimas Maulana',
                'phone' => '08123123123',
                'email' => 'dimas@gmail.com',
                'total' => 40000,
                'shipping_cost' => 38000,
                'shipping_service' => 'REG - Layanan Reguler',
                'payment_method' => 'qris',
                'date' => '04 Sep 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [],
            ],
            [
                'code' => 'ASC-MTMK1MB962',
                'user_id' => 3,
                'customer' => 'Dimas Maulana',
                'phone' => '08123123123',
                'email' => 'dimas@gmail.com',
                'total' => 40000,
                'shipping_cost' => 38000,
                'shipping_service' => 'REG - Layanan Reguler',
                'payment_method' => 'qris',
                'date' => '04 Sep 2026',
                'type' => 'ready',
                'status' => 'Awaiting',
                'order_items' => [],
            ],
        ];

        foreach ($orders as $orderData) {
            $items = $orderData['order_items'] ?? [];
            unset($orderData['order_items']);

            $order = Order::create($orderData);

            foreach ($items as $item) {
                $item['order_id'] = $order->id;
                OrderItem::create($item);
            }
        }
    }
}
