<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductImage;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // === PRODUK ASLI (ID 1-9) ===
            [
                'code' => 'classic-tee',
                'name' => 'Syndicate Classic Teez',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 185000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Sand','hex'=>'#D9CBB0'],['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Off-White','hex'=>'#EFEBE2']]),
                'stock' => json_encode([]),
                'sold' => 126,
                'costs' => json_encode(['production'=>62000, 'kemasan'=>16000, 'stiker'=>11000]),
                'description' => 'Kaos cotton combed 24s dengan sablon plastisol logo Aircooled Syndicate.',
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'boxer-tee',
                'name' => 'Boxer Engine Tee',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 195000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => 12,
                'sold' => 84,
                'costs' => json_encode(['production'=>64000, 'kemasan'=>16000, 'stiker'=>11000]),
                'description' => 'Grafis flat-six engine cutaway di belakang. Bahan heavyweight cotton 16s.',
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'flatsix-cap',
                'name' => 'Flat-Six Cap',
                'category' => 'Topi',
                'type' => 'ready',
                'price' => 165000,
                'weight' => 1000,
                'print_type' => 'text',
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode([['name'=>'Black','hex'=>'#1d1a16'],['name'=>'Khaki','hex'=>'#B7A98A']]),
                'stock' => 54,
                'sold' => 72,
                'costs' => json_encode(['production'=>58000, 'kemasan'=>14000, 'stiker'=>9000]),
                'description' => 'Topi 6-panel unstructured, bordir logo di depan, strap kuningan adjustable. Warna hitam pekat.',
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'pit-tote',
                'name' => 'Pit Crew Tote',
                'category' => 'Goodie Bag',
                'type' => 'ready',
                'price' => 120000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode([['name'=>'Natural','hex'=>'#E4DCC8']]),
                'stock' => 67,
                'sold' => 54,
                'costs' => json_encode(['production'=>38000, 'kemasan'=>13000, 'stiker'=>8000]),
                'description' => 'Tote bag kanvas 12oz natural, sablon logo besar. Muat majalah, helm cap, dan belanjaan part.',
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'heritage-hoodie',
                'name' => 'Heritage Hoodie',
                'category' => 'Hoodie',
                'type' => 'ready',
                'price' => 385000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['S','M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Heather Grey','hex'=>'#B8B5AE'],['name'=>'Charcoal','hex'=>'#26231F']]),
                'stock' => 22,
                'sold' => 41,
                'costs' => json_encode(['production'=>168000, 'kemasan'=>24000, 'stiker'=>16000]),
                'description' => 'Hoodie fleece 320gsm heather grey, kantong kangguru, drawstring kuning. Hangat untuk morning run.',
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'sticker-vol1',
                'name' => 'Sticker Pack Vol.1',
                'category' => 'Stiker',
                'type' => 'ready',
                'price' => 55000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode([['name'=>'Mix','hex'=>'#EFEBE2']]),
                'stock' => 140,
                'sold' => 210,
                'costs' => json_encode(['production'=>14000, 'kemasan'=>8000, 'stiker'=>5000]),
                'description' => 'Set 8 stiker die-cut vinyl tahan air & UV. Tempel di toolbox, laptop, atau bumper.',
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'lemans-tee',
                'name' => 'Le Mans 70 Teex',
                'category' => 'Kaos',
                'type' => 'preorder',
                'price' => 220000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['S','M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Off-White','hex'=>'#EFEBE2'],['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => 0,
                'sold' => 0,
                'costs' => json_encode(['production'=>68000, 'kemasan'=>17000, 'stiker'=>13000]),
                'description' => 'Edisi terbatas memperingati Le Mans 1970. Sablon 3 warna premium di cotton combed 20s.',
                'views' => 153,
                'target' => 50,
                'preorder' => '{"sessionName":"DROP 03","opens":"1 Jun","closes":"30 Jun","target":50,"committed":34,"eta":"25 Jul","status":"open","price":220000,"compareAt":0,"sizes":["S","M","L","XL","XXL"],"colors":[{"name":"Off-White","hex":"#EFEBE2"},{"name":"Sand","hex":"#D9CBB0"}],"costs":{"production":68000,"kemasan":17000,"stiker":13000},"split":{"base":"harga","mediaPct":30,"mediaRole":"ro1","desainPct":30,"desainRole":"ro1","prodPct":25,"prodRole":"ro2","storePct":15},"buyers":[{"name":"Galih Pratomo","items":[{"size":"L","color":"Off-White","qty":1}],"pay":"Lunas","ship":"Belum Terkirim","payAmount":245000,"payMethod":"Transfer BCA","payDate":"12 Jun 2026"},{"name":"Intan Permata","items":[{"size":"M","color":"Sand","qty":1},{"size":"L","color":"Off-White","qty":1}],"pay":"Belum Lunas","ship":"Belum Terkirim"},{"name":"Bagas Saputra","items":[{"size":"XL","color":"Off-White","qty":1}],"pay":"Lunas","ship":"Belum Terkirim","payAmount":245000,"payMethod":"QRIS","payDate":"13 Jun 2026"},{"name":"Maya Lestari","items":[{"size":"S","color":"Sand","qty":2}],"pay":"Belum Lunas","ship":"Belum Terkirim"},{"name":"Rizky Ananda","items":[{"size":"L","color":"Off-White","qty":1}],"pay":"Belum Lunas","ship":"Belum Terkirim"},{"name":"Dewi Anggraini","items":[{"size":"M","color":"Off-White","qty":1}],"pay":"Lunas","ship":"Belum Terkirim","payAmount":245000,"payMethod":"GoPay","payDate":"15 Jun 2026"}]}',
                'sessionHistory' => '[{"sessionName":"DROP 01","opens":"5 Jan","closes":"31 Jan","target":40,"committed":46,"eta":"25 Feb","status":"closed","price":195000,"compareAt":0,"sizes":["S","M","L","XL"],"colors":[{"name":"Off-White","hex":"#EFEBE2"}],"costs":{"production":64000,"kemasan":16000,"stiker":11000},"split":{"base":"gross","mediaPct":30,"mediaRole":"ro1","desainPct":30,"desainRole":"ro1","prodPct":25,"prodRole":"ro2","storePct":15},"buyers":[{"name":"Bayu Pratama","size":"L","color":"Off-White","qty":2,"pay":"Lunas","ship":"Terkirim"},{"name":"Rangga Wijaya","size":"M","color":"Off-White","qty":1,"pay":"Lunas","ship":"Terkirim"},{"name":"Sari Indah","size":"XL","color":"Off-White","qty":1,"pay":"Lunas","ship":"Terkirim"},{"name":"Dimas Aditya","size":"L","color":"Off-White","qty":1,"pay":"Lunas","ship":"Proses"},{"name":"Putri Maharani","size":"S","color":"Off-White","qty":1,"pay":"Lunas","ship":"Terkirim"},{"name":"Wisnu Gunawan","size":"M","color":"Off-White","qty":2,"pay":"Lunas","ship":"Terkirim"},{"name":"Andre Kurnia","size":"XL","color":"Off-White","qty":1,"pay":"Lunas","ship":"Terkirim"},{"name":"Fajar Nugraha","size":"L","color":"Off-White","qty":1,"pay":"Lunas","ship":"Proses"}]}]',
            ],
            [
                'code' => 'club-jacket',
                'name' => 'Air-Cooled Club Jacket',
                'category' => 'Jacket',
                'type' => 'preorder',
                'price' => 650000,
                'weight' => 1000,
                'print_type' => 'text',
                'sizes' => json_encode(['M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Navy','hex'=>'#1a1f2b'],['name'=>'Black','hex'=>'#14110D']]),
                'stock' => 0,
                'sold' => 0,
                'costs' => json_encode(['production'=>340000, 'kemasan'=>30000, 'stiker'=>24000]),
                'description' => 'Coach jacket navy dengan bordir punggung penuh dan patch lengan. Bahan taslan anti air, lining flanel.',
                'views' => 2,
                'target' => 40,
                'preorder' => '{"sessionName":"DROP 03","opens":"1 Jun","closes":"30 Jun","target":30,"committed":12,"eta":"10 Agu","status":"open","price":650000,"compareAt":0,"sizes":["M","L","XL","XXL"],"colors":[{"name":"Navy","hex":"#1a1f2b"},{"name":"Black","hex":"#14110D"}],"costs":{"production":340000,"kemasan":30000,"stiker":24000},"split":{"base":"gross","mediaPct":30,"mediaRole":"ro1","desainPct":30,"desainRole":"ro1","prodPct":25,"prodRole":"ro2","storePct":15},"buyers":[{"name":"Surya Mahendra","items":[{"size":"L","color":"Navy","qty":1}],"pay":"Lunas","ship":"Belum Terkirim","payAmount":680000,"payMethod":"Transfer BCA","payDate":"11 Jun 2026"},{"name":"Anton Wijaya","items":[{"size":"XL","color":"Black","qty":1}],"pay":"Belum Lunas","ship":"Belum Terkirim"},{"name":"Yusuf Hakim","items":[{"size":"M","color":"Navy","qty":1}],"pay":"Belum Lunas","ship":"Belum Terkirim"}]}',
                'sessionHistory' => '[]',
            ],
            [
                'code' => 'rally-goodie',
                'name' => 'Vintage Rally Goodie Set',
                'category' => 'Goodie Bag',
                'type' => 'preorder',
                'price' => 275000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode([['name'=>'Kraft','hex'=>'#CDB892']]),
                'stock' => 0,
                'sold' => 0,
                'costs' => json_encode(['production'=>96000, 'kemasan'=>20000, 'stiker'=>14000]),
                'description' => 'Bundle berisi tote, enamel pin set, patch, dan majalah edisi cetak terbatas. Dikemas dalam box kraft.',
                'views' => 2,
                'target' => 60,
                'preorder' => '{"sessionName":"DROP 02","opens":"1 Mei","closes":"20 Mei","target":40,"committed":40,"eta":"15 Jun","status":"production","price":275000,"compareAt":300000,"sizes":["One Size"],"colors":[{"name":"Kraft","hex":"#CDB892"}],"costs":{"production":96000,"kemasan":20000,"stiker":14000},"split":{"base":"gross","mediaPct":30,"mediaRole":"ro1","desainPct":30,"desainRole":"ro1","prodPct":25,"prodRole":"ro2","storePct":15},"buyers":[{"name":"Prabowo Adi","items":[{"size":"One Size","color":"Kraft","qty":1}],"pay":"Lunas","ship":"Belum Terkirim","payAmount":300000,"payMethod":"Transfer BCA","payDate":"5 Mei 2026"},{"name":"Sinta Dewanti","items":[{"size":"One Size","color":"Kraft","qty":2}],"pay":"Lunas","ship":"Belum Terkirim","payAmount":575000,"payMethod":"QRIS","payDate":"6 Mei 2026"},{"name":"Oka Pranata","items":[{"size":"One Size","color":"Kraft","qty":1}],"pay":"Batal","ship":"Belum Terkirim"},{"name":"Lia Kusuma","items":[{"size":"One Size","color":"Kraft","qty":1}],"pay":"Lunas","ship":"Belum Terkirim","payAmount":300000,"payMethod":"GoPay","payDate":"7 Mei 2026"}]}',
                'sessionHistory' => '[{"sessionName":"DROP 01","opens":"10 Feb","closes":"28 Feb","target":30,"committed":38,"eta":"25 Mar","status":"closed","price":250000,"compareAt":0,"sizes":["One Size"],"colors":[{"name":"Kraft","hex":"#CDB892"}],"costs":{"production":92000,"kemasan":19000,"stiker":12000},"split":{"base":"gross","mediaPct":30,"mediaRole":"ro1","desainPct":30,"desainRole":"ro1","prodPct":25,"prodRole":"ro2","storePct":15},"buyers":[{"name":"Hendra Saputra","size":"One Size","color":"Kraft","qty":1,"pay":"Lunas","ship":"Terkirim"},{"name":"Nadia Rahman","size":"One Size","color":"Kraft","qty":2,"pay":"Lunas","ship":"Terkirim"},{"name":"Yoga Pratama","size":"One Size","color":"Kraft","qty":1,"pay":"Lunas","ship":"Proses"},{"name":"Kirana Dewi","size":"One Size","color":"Kraft","qty":1,"pay":"Lunas","ship":"Terkirim"},{"name":"Reza Maulana","size":"One Size","color":"Kraft","qty":3,"pay":"Lunas","ship":"Terkirim"},{"name":"Lestari W.","size":"One Size","color":"Kraft","qty":1,"pay":"Lunas","ship":"Terkirim"}]}]',
            ],

            // === PRODUK TEST/DUMMY (ID 10-35) ===
            [
                'code' => 'test-product-444',
                'name' => 'Test Product',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 180000,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['S','M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => 10,
                'sold' => 0,
                'costs' => json_encode(['production'=>1, 'kemasan'=>2, 'stiker'=>3]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'pyb-white-233',
                'name' => 'PYB White',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 18500,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['S','M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => 10,
                'sold' => 0,
                'costs' => json_encode(['production'=>1, 'kemasan'=>2, 'stiker'=>3]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'test-2-300',
                'name' => 'Test 2',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 123123,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Off-White','hex'=>'#EFEBE2'],['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => json_encode([]),
                'sold' => 0,
                'costs' => json_encode(['production'=>7, 'kemasan'=>10, 'stiker'=>20]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'test-2-9',
                'name' => 'Test 2',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 123123,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['S','M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Off-White','hex'=>'#EFEBE2'],['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => 10,
                'sold' => 0,
                'costs' => json_encode(['production'=>7, 'kemasan'=>10, 'stiker'=>20]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'test-2-180',
                'name' => 'Test 2',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 123456,
                'weight' => 1000,
                'print_type' => 'logo',
                'sizes' => json_encode(['S','M','L','XL','XXL']),
                'colors' => json_encode([['name'=>'Off-White','hex'=>'#EFEBE2'],['name'=>'Sand','hex'=>'#D9CBB0'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => 10,
                'sold' => 0,
                'costs' => json_encode(['production'=>4, 'kemasan'=>3, 'stiker'=>7]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'test-123-150',
                'name' => 'Test 123',
                'category' => 'Long Sleeve - Non RIB',
                'type' => 'ready',
                'price' => 18920,
                'weight' => 1000,
                'print_type' => 'text',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Off-White','hex'=>'#EFEBE2'],['name'=>'Sand','hex'=>'#D9CBB0'],['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode(['XS'=>11,'S'=>10,'M'=>12,'L'=>9,'XL'=>19,'XXL'=>5]),
                'sold' => 0,
                'costs' => json_encode(['production'=>100, 'kemasan'=>193, 'stiker'=>400]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'wwb-longsleeve-270',
                'name' => 'WWB Longsleeve',
                'category' => 'Long Sleeve - RIB',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'text',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode(['XS'=>10,'S'=>10,'M'=>10,'L'=>10,'XL'=>10,'XXL'=>10,'3L'=>5,'4L'=>5,'5L'=>5,'6L'=>5]),
                'sold' => 0,
                'costs' => json_encode(['production'=>5000, 'kemasan'=>2000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'test-wwb-829',
                'name' => 'Test wwb',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode(['XS'=>10,'S'=>10,'M'=>10,'L'=>10,'XL'=>10,'XXL'=>10,'3L'=>5,'4L'=>5,'5L'=>5,'6L'=>5]),
                'sold' => 0,
                'costs' => json_encode(['production'=>5000, 'kemasan'=>2000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'wwb-test-742',
                'name' => 'WWB Test',
                'category' => 'Long Sleeve - RIB',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode(['XS'=>10,'S'=>13,'M'=>11,'L'=>10,'XL'=>10,'XXL'=>5,'3L'=>9,'4L'=>5,'5L'=>5,'6L'=>5]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>2000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'acs-vw-longsleeve-730',
                'name' => 'ACS VW Longsleeve',
                'category' => 'Long Sleeve - Non RIB',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 3,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b'],['name'=>'Kraft','hex'=>'#CDB892']]),
                'stock' => json_encode(['XS'=>10,'S'=>10,'M'=>10,'L'=>10,'XL'=>10,'XXL'=>5,'3L'=>5,'4L'=>6,'5L'=>6,'6L'=>6]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>1000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'test-wwb-lagi-395',
                'name' => 'Test WWB Lagi',
                'category' => 'Long Sleeve - RIB',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode(['XS'=>10,'S'=>10,'M'=>10,'L'=>10,'XL'=>7,'XXL'=>7,'3L'=>7,'4L'=>7,'5L'=>7,'6L'=>7]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>1000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'ls-acs-645',
                'name' => 'LS ACS',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 4,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode(['XS'=>10,'S'=>10,'M'=>10,'L'=>10,'XL'=>10,'XXL'=>8,'3L'=>8,'4L'=>8,'5L'=>8,'6L'=>8]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>1000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'pyb-123-327',
                'name' => 'PYB 123',
                'category' => 'Long Sleeve - Non RIB',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 1,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Charcoal','hex'=>'#26231F'],['name'=>'Black','hex'=>'#14110D'],['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode(['XS'=>12,'S'=>10,'M'=>10,'L'=>10,'XL'=>10,'XXL'=>10,'3L'=>10,'4L'=>10,'5L'=>10,'6L'=>10]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>1000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'ac-vwprs-847',
                'name' => 'ac vwprs 123',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 4,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Off-White','hex'=>'#EFEBE2'],['name'=>'Sand','hex'=>'#D9CBB0'],['name'=>'Heather Grey','hex'=>'#B8B5AE']]),
                'stock' => json_encode(['XS'=>10,'S'=>7,'M'=>7,'L'=>7,'XL'=>6,'XXL'=>7,'3L'=>7,'4L'=>7,'5L'=>7,'6L'=>7]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>2000, 'stiker'=>1000]),
                'description' => null,
                'views' => 2,
                'target' => 0,
            ],
            [
                'code' => 'siker-1-673',
                'name' => 'Siker 1',
                'category' => 'Stiker',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 5,
                'print_type' => 'logo',
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode([]),
                'stock' => json_encode(['One Size'=>28]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>1000, 'stiker'=>1000]),
                'description' => null,
                'views' => 0,
                'target' => 0,
            ],
            [
                'code' => 'stiker-dua-975',
                'name' => 'Stiker Dua',
                'category' => 'Stiker',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 5,
                'print_type' => 'logo',
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode([]),
                'stock' => json_encode(['One Size'=>0]),
                'sold' => 0,
                'costs' => json_encode(['production'=>10, 'kemasan'=>10, 'stiker'=>10]),
                'description' => null,
                'views' => 6,
                'target' => 0,
            ],
            [
                'code' => 'pyb-a1-912',
                'name' => 'PYB A1',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 1,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Black','hex'=>'#14110D']]),
                'stock' => json_encode(['XS'=>10,'S'=>10,'M'=>10,'L'=>10,'XL'=>10,'XXL'=>9,'3L'=>10,'4L'=>10,'5L'=>10,'6L'=>10]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>1000, 'stiker'=>1000]),
                'description' => null,
                'views' => 20,
                'target' => 0,
            ],
            [
                'code' => 'wwb-preorder-799',
                'name' => 'wwb preorder',
                'category' => 'Long Sleeve - RIB',
                'type' => 'preorder',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Navy','hex'=>'#1a1f2b']]),
                'stock' => json_encode([]),
                'sold' => 0,
                'costs' => json_encode(['production'=>6000, 'kemasan'=>500, 'stiker'=>1000]),
                'description' => null,
                'views' => 12,
                'target' => 0,
            ],
            [
                'code' => 'acs-pre-order-392',
                'name' => 'acs pre order',
                'category' => 'Kaos',
                'type' => 'preorder',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 3,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => json_encode([]),
                'sold' => 0,
                'costs' => json_encode(['production'=>5000, 'kemasan'=>1000, 'stiker'=>2000]),
                'description' => null,
                'views' => 4,
                'target' => 0,
            ],
            [
                'code' => 'ls-acs-pre-377',
                'name' => 'LS ACS PRE',
                'category' => 'Kaos',
                'type' => 'preorder',
                'price' => 1000,
                'weight' => 1000,
                'product_parent_id' => 4,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Off-White','hex'=>'#EFEBE2']]),
                'stock' => json_encode([]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>2000, 'stiker'=>5000]),
                'description' => null,
                'views' => 4,
                'target' => 20,
            ],
            [
                'code' => 'wwb-pre-sesi-156',
                'name' => 'WWB Pre Sesi',
                'category' => 'Kaos',
                'type' => 'preorder',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => json_encode([]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>1000, 'stiker'=>1000]),
                'description' => null,
                'views' => 2,
                'target' => 50,
            ],
            [
                'code' => 'pyb-pre-order-567',
                'name' => 'PYB Pre Order',
                'category' => 'Kaos',
                'type' => 'preorder',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 1,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => json_encode([]),
                'sold' => 0,
                'costs' => json_encode(['production'=>100, 'kemasan'=>200, 'stiker'=>300]),
                'description' => null,
                'views' => 4,
                'target' => 0,
            ],
            [
                'code' => 'wwb-pre-order-719',
                'name' => 'WWB Pre Order',
                'category' => 'Kaos',
                'type' => 'preorder',
                'price' => 22000,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => json_encode(['XS'=>10,'S'=>3,'M'=>2,'L'=>2,'XL'=>2,'XXL'=>2,'3L'=>1,'4L'=>2,'5L'=>1,'6L'=>1]),
                'sold' => 0,
                'costs' => json_encode(['production'=>1000, 'kemasan'=>2000, 'stiker'=>3000]),
                'description' => null,
                'views' => 10,
                'target' => 0,
            ],
            [
                'code' => 'pym-234',
                'name' => 'PYM',
                'category' => 'Kaos',
                'type' => 'preorder',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 1,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => json_encode([]),
                'sold' => 0,
                'costs' => json_encode(['production'=>2000, 'kemasan'=>2000, 'stiker'=>2000]),
                'description' => null,
                'views' => 2,
                'target' => 30,
            ],
            [
                'code' => 'wwnda-506',
                'name' => 'wwnda',
                'category' => 'Kaos',
                'type' => 'ready',
                'price' => 0,
                'weight' => 1000,
                'product_parent_id' => 2,
                'print_type' => 'logo',
                'sizes' => json_encode(['XS','S','M','L','XL','XXL','3L','4L','5L','6L']),
                'colors' => json_encode([['name'=>'Sand','hex'=>'#D9CBB0']]),
                'stock' => json_encode(['XS'=>4,'S'=>4,'M'=>4,'L'=>4,'XL'=>4,'XXL'=>4,'3L'=>4,'4L'=>4,'5L'=>4,'6L'=>4]),
                'sold' => 0,
                'costs' => json_encode(['production'=>300, 'kemasan'=>200, 'stiker'=>100]),
                'description' => null,
                'views' => 7,
                'target' => 0,
            ],
        ];

        foreach ($products as $prod) {
            $p = Product::create($prod);
            $p->productImages()->create(['src' => '/logo.jpg']);
        }
    }
}
